---
- name: Metricbeat installation play
  hosts: webservers
  become: yes
  tasks:

  - name: Install metricbeat deb package from internet
    apt:
      deb: https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.6.1-amd64.deb

  - name: drop mbeat yml to webservers
    copy:
      src: /etc/ansible/files/metricbeat.yml
      dest: /etc/metricbeat/

  - name: enable mbeat docker
    command: metricbeat modules enable docker

  - name: setup mbeat
    command: metricbeat setup
    
  - name: enable at boot
    systemd:
      name: metricbeat
      enabled: yes
~                      